language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t dav/playground -f Dockerfile.dev .

script:
  - docker run -e CI=true dav/playground npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "dq-docker"
  env: "Dqdocker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-751855496248"
  bucket_path: "dq-docker"
  on:
    branch: develop
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
